---
- name: Deploy 3 node cassandra cluster
  hosts: cassandra
  pre_tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - curl
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      sudo: True
    - role: cassandra
      become: True
